#!/usr/bin/env bash
#install ngix and have a file that returns the string "Hello World  inside

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chmod -R 755 /var/www/html/
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
